cp4ba:
 namespace: gitops-cp-filenet
 db_server: "161.202.168.37"
 #odm_db_name: "odmdb"
 db_port: "50000"
 db_type: "db2"
 #odm_image_repository: "cp.icr.io/cp/cp4a/odm"
 #odm_image_tag: "21.0.3-IF002"
 #odm_image_version: "21.0.3"